from DVD import DVD
from Book import Book
from Magazine import Magazine

hamilton = DVD(False,True,True,22,"Hamilton","History, Musical")

death_on_the_nile = Book(False,True,True,50,"Death on Nielsen","Agatha Christie",520)

hero_of_the_week = Magazine(False,True,True,10,"Hero of The Week","Hero img")
print("************DVD***************")
hamilton.overdue()
hamilton.late_fee_calculation()
hamilton.check_availability()
hamilton.borrow()
hamilton.check_availability()
hamilton.play()
print(hamilton.price)
hamilton.late_fee_calculation()
print(hamilton.price)
hamilton.overdue()
hamilton.return_it()
hamilton.check_availability()
print()

print("************Book***************")
death_on_the_nile.overdue()
death_on_the_nile.late_fee_calculation()
death_on_the_nile.check_availability()
death_on_the_nile.borrow()
death_on_the_nile.check_availability()
death_on_the_nile.switch_pages()
print(death_on_the_nile.price)
death_on_the_nile.late_fee_calculation()
print(death_on_the_nile.price)
death_on_the_nile.overdue()
death_on_the_nile.return_it()
death_on_the_nile.check_availability()

print()
print("************Magazine***************")
hero_of_the_week.overdue()
hero_of_the_week.late_fee_calculation()
hero_of_the_week.check_availability()
hero_of_the_week.borrow()
hero_of_the_week.check_availability()
hero_of_the_week.change_cover()
print(hero_of_the_week.price)
hero_of_the_week.late_fee_calculation()
print(hero_of_the_week.price)
hero_of_the_week.overdue()
hero_of_the_week.return_it()
hero_of_the_week.check_availability()