# Generated by Django 5.2.7 on 2025-10-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_ninjas_created_at_ninjas_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninjas',
            name='dojo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='myApp.dojo'),
        ),
    ]
