# Generated by Django 5.2.7 on 2025-10-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='messages',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='users',
        ),
    ]
