# Generated by Django 5.2.7 on 2025-10-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='wrote_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wrote_by', to='myApp.user'),
            preserve_default=False,
        ),
    ]
