# Generated by Django 5.2.7 on 2025-10-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_message_wrote_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
